version: "3.8"

services:
  db:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking
    ports:
      - 5432:5432
    volumes:
      - prisma:/var/lib/postgresql/data/

  node:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/booking

volumes:
  prisma: ~

